### ISSUE TITLE
Jibri server side recording stopped working after migrating from stable-9823 --> stable-9955 (Docker image)

### ISSUE THREAD

**Issue by sgabenov** [jitsi/jibri#557]
## Description
On latest stable version of docker image "stable-9955" stoped working function of server side recording of session. I have tested several previous stable releases and it works correct when using them

## Current behavior
On UI have an error "Could not start recording"
On backend logs - error of connecting jibri user to session.

## Expected Behavior
Could start a recording

## Possible Solution
Some changes on xmpp side of working with recorder account

## Steps to reproduce
start docker compose

# Environment details

Docker compose:
```
cat docker-compose.yml
version: "3.5"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "10"

services:
  # Frontend
  web:
    image: jitsi/web:${JITSI_IMAGE_VERSION:-unstable}
    container_name: web
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${HTTP_PORT}:80'
      - '${HTTPS_PORT}:443'
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
      - ${CONFIG}/web/images/welcome-background.png:/usr/share/jitsi-meet/images/welcome-background.png:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      - ${CONFIG}/ssl/fullchain.pem:/config/keys/cert.crt:ro
      - ${CONFIG}/ssl/privkey.pem:/config/keys/cert.key:ro
    environment:
      - AMPLITUDE_ID
      - ANALYTICS_SCRIPT_URLS
      - ANALYTICS_WHITELISTED_EVENTS
      - AUDIO_QUALITY_OPUS_BITRATE
      - AUTO_CAPTION_ON_RECORD
      - BRANDING_DATA_URL
      - CALLSTATS_CUSTOM_SCRIPT_URL
      - CALLSTATS_ID
      - CALLSTATS_SECRET
      - CHROME_EXTENSION_BANNER_JSON
      - COLIBRI_WEBSOCKET_PORT
      - CONFCODE_URL
      - CONFIG_EXTERNAL_CONNECT
      - DEFAULT_LANGUAGE
      - DEPLOYMENTINFO_ENVIRONMENT
      - DEPLOYMENTINFO_ENVIRONMENT_TYPE
      - DEPLOYMENTINFO_REGION
      - DEPLOYMENTINFO_SHARD
      - DEPLOYMENTINFO_USERREGION
      - DESKTOP_SHARING_FRAMERATE_MIN
      - DESKTOP_SHARING_FRAMERATE_MAX
      - DIALIN_NUMBERS_URL
      - DIALOUT_AUTH_URL
      - DIALOUT_CODES_URL
      - DISABLE_AUDIO_LEVELS
      - DISABLE_DEEP_LINKING
      - DISABLE_GRANT_MODERATOR
      - DISABLE_HTTPS
      - DISABLE_KICKOUT
      - DISABLE_LOCAL_RECORDING
      - DISABLE_POLLS
      - DISABLE_PRIVATE_CHAT
      - DISABLE_PROFILE
      - DISABLE_REACTIONS
      - DISABLE_REMOTE_VIDEO_MENU
      - DISABLE_START_FOR_ALL
      - DROPBOX_APPKEY
      - DROPBOX_REDIRECT_URI
      - DYNAMIC_BRANDING_URL
      - ENABLE_AUDIO_PROCESSING
      - ENABLE_AUTH
      - ENABLE_BREAKOUT_ROOMS
      - ENABLE_CALENDAR
      - ENABLE_COLIBRI_WEBSOCKET
      - ENABLE_E2EPING
      - ENABLE_FILE_RECORDING_SHARING
      - ENABLE_GUESTS
      - ENABLE_HSTS
      - ENABLE_HTTP_REDIRECT
      - ENABLE_IPV6
      - ENABLE_LETSENCRYPT
      - ENABLE_LIPSYNC
      - ENABLE_NO_AUDIO_DETECTION
      - ENABLE_NOISY_MIC_DETECTION
      - ENABLE_OCTO
      - ENABLE_OPUS_RED
      - ENABLE_PREJOIN_PAGE
      - ENABLE_P2P
      - ENABLE_WELCOME_PAGE
      - ENABLE_CLOSE_PAGE
      - ENABLE_LIVESTREAMING
      - ENABLE_LIVESTREAMING_DATA_PRIVACY_LINK
      - ENABLE_LIVESTREAMING_HELP_LINK
      - ENABLE_LIVESTREAMING_TERMS_LINK
      - ENABLE_LIVESTREAMING_VALIDATOR_REGEXP_STRING
      - ENABLE_LOCAL_RECORDING_NOTIFY_ALL_PARTICIPANT
      - ENABLE_LOCAL_RECORDING_SELF_START
      - ENABLE_RECORDING
      - ENABLE_REMB
      - ENABLE_REQUIRE_DISPLAY_NAME
      - ENABLE_SERVICE_RECORDING
      - ENABLE_SIMULCAST
      - ENABLE_STATS_ID
      - ENABLE_STEREO
      - ENABLE_SUBDOMAINS
      - ENABLE_TALK_WHILE_MUTED
      - ENABLE_TCC
      - ENABLE_TRANSCRIPTIONS
      - ENABLE_XMPP_WEBSOCKET
      - ENABLE_JAAS_COMPONENTS
      - ETHERPAD_PUBLIC_URL
      - ETHERPAD_URL_BASE
      - E2EPING_NUM_REQUESTS
      - E2EPING_MAX_CONFERENCE_SIZE
      - E2EPING_MAX_MESSAGE_PER_SECOND
      - GOOGLE_ANALYTICS_ID
      - GOOGLE_API_APP_CLIENT_ID
      - HIDE_PREMEETING_BUTTONS
      - HIDE_PREJOIN_DISPLAY_NAME
      - HIDE_PREJOIN_EXTRA_BUTTONS
      - INVITE_SERVICE_URL
      - LETSENCRYPT_DOMAIN
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_USE_STAGING
      - MATOMO_ENDPOINT
      - MATOMO_SITE_ID
      - MICROSOFT_API_APP_CLIENT_ID
      - NGINX_RESOLVER
      - NGINX_WORKER_PROCESSES
      - NGINX_WORKER_CONNECTIONS
      - PEOPLE_SEARCH_URL
      - PREFERRED_LANGUAGE
      - PUBLIC_URL
      - P2P_PREFERRED_CODEC
      - RESOLUTION
      - RESOLUTION_MIN
      - RESOLUTION_WIDTH
      - RESOLUTION_WIDTH_MIN
      - START_AUDIO_MUTED
      - START_AUDIO_ONLY
      - START_BITRATE
      - START_SILENT
      - START_WITH_AUDIO_MUTED
      - START_VIDEO_MUTED
      - START_WITH_VIDEO_MUTED
      - TESTING_CAP_SCREENSHARE_BITRATE
      - TESTING_OCTO_PROBABILITY
      - TOKEN_AUTH_URL
      - TOOLBAR_BUTTONS
      - TRANSLATION_LANGUAGES
      - TRANSLATION_LANGUAGES_HEAD
      - TZ
      - USE_APP_LANGUAGE
      - VIDEOQUALITY_BITRATE_H264_LOW
      - VIDEOQUALITY_BITRATE_H264_STANDARD
      - VIDEOQUALITY_BITRATE_H264_HIGH
      - VIDEOQUALITY_BITRATE_VP8_LOW
      - VIDEOQUALITY_BITRATE_VP8_STANDARD
      - VIDEOQUALITY_BITRATE_VP8_HIGH
      - VIDEOQUALITY_BITRATE_VP9_LOW
      - VIDEOQUALITY_BITRATE_VP9_STANDARD
      - VIDEOQUALITY_BITRATE_VP9_HIGH
      - VIDEOQUALITY_ENFORCE_PREFERRED_CODEC
      - VIDEOQUALITY_PREFERRED_CODEC
      - XMPP_AUTH_DOMAIN
      - XMPP_BOSH_URL_BASE
      - XMPP_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - XMPP_PORT
      - WHITEBOARD_ENABLED
      - WHITEBOARD_COLLAB_SERVER_PUBLIC_URL
    networks:
      - meet.jitsi
    logging: *default-logging

  # XMPP server
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    container_name: prosody
    restart: ${RESTART_POLICY:-unless-stopped}
    expose:
      - '${XMPP_PORT:-5222}'
      - '${PROSODY_S2S_PORT:-5269}'
      - '5347'
      - '5280'
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    environment:
      - AUTH_TYPE
      - DISABLE_POLLS
      - ENABLE_AUTH
      - ENABLE_AV_MODERATION
      - ENABLE_BREAKOUT_ROOMS
      - ENABLE_END_CONFERENCE
      - ENABLE_GUESTS
      - ENABLE_IPV6
      - ENABLE_LOBBY
      - ENABLE_RECORDING
      - ENABLE_XMPP_WEBSOCKET
      - ENABLE_JAAS_COMPONENTS
      - GC_TYPE
      - GC_INC_TH
      - GC_INC_SPEED
      - GC_INC_STEP_SIZE
      - GC_GEN_MIN_TH
      - GC_GEN_MAX_TH
      - GLOBAL_CONFIG
      - GLOBAL_MODULES
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JICOFO_AUTH_PASSWORD
      - JICOFO_COMPONENT_SECRET
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JWT_APP_ID
      - JWT_APP_SECRET
      - JWT_ACCEPTED_ISSUERS
      - JWT_ACCEPTED_AUDIENCES
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_ENABLE_DOMAIN_VERIFICATION
      - JWT_TOKEN_AUTH_MODULE
      - MATRIX_UVS_URL
      - MATRIX_UVS_ISSUER
      - MATRIX_UVS_AUTH_TOKEN
      - MATRIX_UVS_SYNC_POWER_LEVELS
      - LOG_LEVEL
      - LDAP_AUTH_METHOD
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_VERSION
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - LDAP_URL
      - LDAP_USE_TLS
      - MAX_PARTICIPANTS
      - PROSODY_AUTH_TYPE
      - PROSODY_RESERVATION_ENABLED
      - PROSODY_RESERVATION_REST_BASE_URL
      - PROSODY_ENABLE_RATE_LIMITS
      - PROSODY_RATE_LIMIT_LOGIN_RATE
      - PROSODY_RATE_LIMIT_SESSION_RATE
      - PROSODY_RATE_LIMIT_TIMEOUT
      - PROSODY_RATE_LIMIT_ALLOW_RANGES
      - PROSODY_RATE_LIMIT_CACHE_SIZE
      - PUBLIC_URL
      - TURN_CREDENTIALS
      - TURN_HOST
      - TURNS_HOST
      - TURN_PORT
      - TURNS_PORT
      - TURN_TRANSPORT
      - TZ
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_MUC_CONFIGURATION
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN
      - XMPP_PORT
    networks:
      meet.jitsi:
        aliases:
          - ${XMPP_SERVER:-xmpp.meet.jitsi}
    logging: *default-logging

  # Focus component
  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-unstable}
    container_name: jicofo
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '127.0.0.1:${JICOFO_REST_PORT:-8888}:8888'
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    environment:
      - AUTH_TYPE
      - BRIDGE_AVG_PARTICIPANT_STRESS
      - BRIDGE_STRESS_THRESHOLD
      - ENABLE_AUTH
      - ENABLE_AUTO_OWNER
      - ENABLE_CODEC_VP8
      - ENABLE_CODEC_VP9
      - ENABLE_CODEC_H264
      - ENABLE_CODEC_OPUS_RED
      - ENABLE_JVB_XMPP_SERVER
      - ENABLE_OCTO
      - ENABLE_RECORDING
      - ENABLE_SCTP
      - ENABLE_AUTO_LOGIN
      - JICOFO_AUTH_LIFETIME
      - JICOFO_AUTH_PASSWORD
      - JICOFO_AUTH_TYPE
      - JICOFO_BRIDGE_REGION_GROUPS
      - JICOFO_ENABLE_AUTH
      - JICOFO_ENABLE_BRIDGE_HEALTH_CHECKS
      - JICOFO_CONF_INITIAL_PARTICIPANT_WAIT_TIMEOUT
      - JICOFO_CONF_SINGLE_PARTICIPANT_TIMEOUT
      - JICOFO_CONF_SOURCE_SIGNALING_DELAYS
      - JICOFO_CONF_MAX_AUDIO_SENDERS
      - JICOFO_CONF_MAX_VIDEO_SENDERS
      - JICOFO_CONF_STRIP_SIMULCAST
      - JICOFO_CONF_SSRC_REWRITING
      - JICOFO_ENABLE_HEALTH_CHECKS
      - JICOFO_ENABLE_REST
      - JICOFO_HEALTH_CHECKS_USE_PRESENCE
      - JICOFO_MULTI_STREAM_BACKWARD_COMPAT
      - JICOFO_OCTO_REGION
      - JIBRI_BREWERY_MUC
      - JIBRI_REQUEST_RETRIES
      - JIBRI_PENDING_TIMEOUT
      - JIGASI_BREWERY_MUC
      - JIGASI_SIP_URI
      - JVB_BREWERY_MUC
      - JVB_XMPP_AUTH_DOMAIN
      - JVB_XMPP_INTERNAL_MUC_DOMAIN
      - JVB_XMPP_PORT
      - JVB_XMPP_SERVER
      - MAX_BRIDGE_PARTICIPANTS
      - OCTO_BRIDGE_SELECTION_STRATEGY
      - SENTRY_DSN="${JICOFO_SENTRY_DSN:-0}"
      - SENTRY_ENVIRONMENT
      - SENTRY_RELEASE
      - TZ
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - XMPP_SERVER
      - XMPP_PORT
    depends_on:
      - prosody
    networks:
      meet.jitsi:
    logging: *default-logging

  # Video bridge
  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-unstable}
    container_name: jvb
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
      - '127.0.0.1:${JVB_COLIBRI_PORT:-8080}:8080'
    volumes:
      - ${CONFIG}/jvb:/config:Z
    environment:
      - DOCKER_HOST_ADDRESS
      - ENABLE_COLIBRI_WEBSOCKET
      - ENABLE_JVB_XMPP_SERVER
      - ENABLE_OCTO
      - JVB_ADVERTISE_IPS
      - JVB_ADVERTISE_PRIVATE_CANDIDATES
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JVB_DISABLE_STUN
      - JVB_PORT
      - JVB_MUC_NICKNAME
      - JVB_STUN_SERVERS
      - JVB_OCTO_BIND_ADDRESS
      - JVB_OCTO_REGION
      - JVB_OCTO_RELAY_ID
      - JVB_WS_DOMAIN
      - JVB_WS_SERVER_ID
      - JVB_XMPP_AUTH_DOMAIN
      - JVB_XMPP_INTERNAL_MUC_DOMAIN
      - JVB_XMPP_PORT
      - JVB_XMPP_SERVER
      - PUBLIC_URL
      - SENTRY_DSN="${JVB_SENTRY_DSN:-0}"
      - SENTRY_ENVIRONMENT
      - SENTRY_RELEASE
      - COLIBRI_REST_ENABLED
      - SHUTDOWN_REST_ENABLED
      - TZ
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - XMPP_PORT
    depends_on:
      - prosody
    networks:
      meet.jitsi:
    logging: *default-logging

  # Recording service
  jibri:
    image: jitsi/jibri:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    labels:
      service: "jitsi-jibri"
    container_name: jibri
    volumes:
      - ${CONFIG}/jibri:/config:Z
      - nfs_volume:/mnt/nfs
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    environment:
      - AUTOSCALER_SIDECAR_KEY_FILE
      - AUTOSCALER_SIDECAR_KEY_ID
      - AUTOSCALER_SIDECAR_GROUP_NAME
      - AUTOSCALER_SIDECAR_HOST_ID
      - AUTOSCALER_SIDECAR_INSTANCE_ID
      - AUTOSCALER_SIDECAR_PORT
      - AUTOSCALER_SIDECAR_REGION
      - AUTOSCALER_SIDECAR_SHUTDOWN_POLLING_INTERVAL
      - AUTOSCALER_SIDECAR_STATS_POLLING_INTERVAL
      - AUTOSCALER_URL
      - CHROMIUM_FLAGS
      - DISPLAY=:0
      - ENABLE_STATS_D
      - IGNORE_CERTIFICATE_ERRORS
      - JIBRI_WEBHOOK_SUBSCRIBERS
      - JIBRI_INSTANCE_ID
      - JIBRI_ENABLE_PROMETHEUS
      - JIBRI_HTTP_API_EXTERNAL_PORT
      - JIBRI_HTTP_API_INTERNAL_PORT
      - JIBRI_RECORDING_RESOLUTION
      - JIBRI_RECORDING_VIDEO_ENCODE_PRESET
      - JIBRI_RECORDING_CONSTANT_RATE_FACTOR
      - JIBRI_RECORDING_FRAMERATE
      - JIBRI_RECORDING_QUEUE_SIZE
      - JIBRI_RECORDING_STREAMING_MAX_BITRATE
      - JIBRI_USAGE_TIMEOUT
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_XORG_HORIZ_SYNC
      - JIBRI_XORG_VERT_REFRESH
      - JIBRI_BREWERY_MUC
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JIBRI_RECORDING_DIR
      - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
      - JIBRI_STRIP_DOMAIN_JID
      - JIBRI_STATSD_HOST
      - JIBRI_STATSD_PORT
      - LOCAL_ADDRESS
      - PUBLIC_URL
      - TZ
      - XMPP_AUTH_DOMAIN
      - XMPP_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_HIDDEN_DOMAIN
      - XMPP_SERVER
      - XMPP_PORT
      - XMPP_RECORDER_DOMAIN
      - XMPP_TRUST_ALL_CERTS
    depends_on:
      - jicofo
    networks:
      meet.jitsi:


# NFS volume to store Jibri recordings on Synology NAS
volumes:
  nfs_volume:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nas01.my.domain,rw,nolock,soft
      device: ":/volume1/recordings"

# Custom network so all services can communicate using a FQDN
networks:
  meet.jitsi:
    name: "prod"
    driver: bridge
    external: true
```

.env 
```
cat .env
# shellcheck disable=SC2034

################################################################################
################################################################################
# Welcome to the Jitsi Meet Docker setup!
#
# This .env file contains some basic options to get you started.
# The full options reference can be found here:
# https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
################################################################################
################################################################################


# # # # # # # # # # # # # # # # # # # # # #
#  JITSI MEET MAIN CONFIGURATION SECTION  #
# # # # # # # # # # # # # # # # # # # # # #

# # # # #
# Basic configuration options
#

# Directory where all configuration will be stored
CONFIG=/data/jitsi

# Exposed HTTP port
HTTP_PORT=8000

# Exposed HTTPS port
HTTPS_PORT=8443

# System time zone
TZ=Europe/Moscow

# Public URL for the web service (required)
PUBLIC_URL=https://my.domain

# Media IP addresses to advertise by the JVB
# This setting deprecates DOCKER_HOST_ADDRESS, and supports a comma separated list of IPs
# See the "Running behind NAT or on a LAN environment" section in the Handbook:
# https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-nat-or-on-a-lan-environment
JVB_ADVERTISE_IPS=10.18.3.26

#
# Memory limits for Java components
#

#JICOFO_MAX_MEMORY=3072m
#VIDEOBRIDGE_MAX_MEMORY=3072m


# # # # #
# Features configuration (config.js)
#

# Control whether the lobby feature should be enabled or not
ENABLE_LOBBY=1

# Control whether the A/V moderation should be enabled or not
ENABLE_AV_MODERATION=1

# Show a prejoin page before entering a conference
ENABLE_PREJOIN_PAGE=1

# Enable the welcome page
ENABLE_WELCOME_PAGE=1

# Enable the close page
ENABLE_CLOSE_PAGE=0

# Disable measuring of audio levels
DISABLE_AUDIO_LEVELS=0

# Enable noisy mic detection
ENABLE_NOISY_MIC_DETECTION=1

# Enable breakout rooms
ENABLE_BREAKOUT_ROOMS=1


# # # # #
# Authentication configuration (see handbook for details)
#

# Enable authentication
ENABLE_AUTH=1

# Enable guest access
ENABLE_GUESTS=1

# Select authentication type: internal, jwt, ldap or matrix
AUTH_TYPE=ldap

# Enable auto login
ENABLE_AUTO_LOGIN=1

# Select session timeout value for an authenticated user
JICOFO_AUTH_LIFETIME=4320 hours


#
# JWT authentication
#

# Application identifier
#JWT_APP_ID=my_jitsi_app_id

# Application secret known only to your token generator
#JWT_APP_SECRET=my_jitsi_app_secret

# (Optional) Set asap_accepted_issuers as a comma separated list
#JWT_ACCEPTED_ISSUERS=my_web_client,my_app_client

# (Optional) Set asap_accepted_audiences as a comma separated list
#JWT_ACCEPTED_AUDIENCES=my_server1,my_server2


#
# LDAP authentication (for more information see the Cyrus SASL saslauthd.conf man page)
#

# LDAP url for connection
LDAP_URL=ldaps://ds.my.domain:636/

# LDAP base DN. Can be empty
LDAP_BASE=cn=users,cn=accounts,dc=avroid,dc=tech

# LDAP user DN. Do not specify this parameter for the anonymous bind
LDAP_BINDDN=uid=svc_ipa,cn=users,cn=accounts,dc=avroid,dc=tech

# LDAP user password. Do not specify this parameter for the anonymous bind
LDAP_BINDPW=<password>

# LDAP filter. Tokens example:
# %1-9 - if the input key is user@mail.domain.com, then %1 is com, %2 is domain and %3 is mail
# %s - %s is replaced by the complete service string
# %r - %r is replaced by the complete realm string
LDAP_FILTER=(&(uid=%u)(objectClass=posixAccount))

# LDAP authentication method
LDAP_AUTH_METHOD=bind

# LDAP version
LDAP_VERSION=3

# LDAP TLS using
LDAP_USE_TLS=1

# List of SSL/TLS ciphers to allow
LDAP_TLS_CIPHERS=SECURE256:SECURE128:!AES-128-CBC:!ARCFOUR-128:!CAMELLIA-128-CBC:!3DES-CBC:!CAMELLIA-128-CBC

# Require and verify server certificate
LDAP_TLS_CHECK_PEER=0

# Path to CA cert file. Used when server certificate verify is enabled
LDAP_TLS_CACERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Path to CA certs directory. Used when server certificate verify is enabled
LDAP_TLS_CACERT_DIR=/etc/ssl/certs

# Wether to use starttls, implies LDAPv3 and requires ldap:// instead of ldaps://
LDAP_START_TLS=0


# # # # #
# Security
#

# Set these to strong passwords to avoid intruders from impersonating a service account
# The service(s) won't start unless these are specified
# Running ./gen-passwords.sh will update .env with strong passwords
# You may skip the Jigasi and Jibri passwords if you are not using those
# DO NOT reuse passwords
#

# XMPP password for Jicofo client connections
JICOFO_AUTH_PASSWORD=02fdd4ee60326334452e3bca6b142330

# XMPP password for JVB client connections
JVB_AUTH_PASSWORD=02fdd4ee60326334452e3bca6b142330

# XMPP password for Jigasi MUC client connections
JIGASI_XMPP_PASSWORD=02fdd4ee60326334452e3bca6b142330

# XMPP recorder user and password for Jibri client connections
JIBRI_RECORDER_USER=recorder
JIBRI_RECORDER_PASSWORD=02fdd4ee60326334452e3bca6b142330

# XMPP user and password for Jibri client connections
JIBRI_XMPP_USER=jibri
JIBRI_XMPP_PASSWORD=02fdd4ee60326334452e3bca6b142330


# # # # #
# Advanced configuration
#

# These configuration options are already set and generally don't need to be changed.
#

# Internal XMPP domain (default: meet.jitsi)
XMPP_DOMAIN=meet.jitsi

# Internal XMPP domain for authenticated services (default: auth.meet.jitsi)
XMPP_AUTH_DOMAIN=auth.meet.jitsi

# Internal XMPP server name xmpp.meet.jitsi (default: xmpp.meet.jitsi)
XMPP_SERVER=xmpp.meet.jitsi

# Internal XMPP server URL for BOSH module
#XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280

# XMPP domain for the MUC (default: muc.meet.jitsi)
XMPP_MUC_DOMAIN=muc.meet.jitsi

# XMPP domain for the internal MUC (default: internal-muc.meet.jitsi)
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi

# XMPP domain for unauthenticated users (default: guest.meet.jitsi)
XMPP_GUEST_DOMAIN=guest.meet.jitsi

# Domain for the jibri recorder (default: recorder.meet.jitsi)
XMPP_RECORDER_DOMAIN=recorder.meet.jitsi

# Custom Prosody modules for XMPP_DOMAIN (comma separated)
#XMPP_MODULES=info,alert

# Custom Prosody modules for MUC component (comma separated)
# XMPP_MUC_MODULES=info,alert

# Custom Prosody modules for internal MUC component (comma separated)
#XMPP_INTERNAL_MUC_MODULES=info,alert

# Custom prosody modules to load in global configuration (comma separated)
#GLOBAL_MODULES=statistics,alert

# Custom configuration string with escaped newlines
#GLOBAL_CONFIG="foo = bar;\nkey = val;"

# Handle TLS connections outside of this setup
#DISABLE_HTTPS=0

# Redirect HTTP traffic to HTTPS
#ENABLE_HTTP_REDIRECT=0

# Controls which logs are output from prosody and associated modules
#LOG_LEVEL=info

# Send a strict-transport-security header to force browsers to use a secure and trusted connection.
# Recommended for production use.
#ENABLE_HSTS=1

# Provides means to disable IPv6 in environments that don't support it
#ENABLE_IPV6=0

# Enabled older unsafe regex for JVB colibri-ws URLs. WARNING: Enable with caution,
# this regex allows connections to arbitrary internal IP addresses and is not recommended for production use.
# Unsafe regex is defined as [a-zA-Z0-9-\._]+
#ENABLE_COLIBRI_WEBSOCKET_UNSAFE_REGEX=0

# DNS name to look up JVB IP address, used for default value of COLIBRI_WEBSOCKET_REGEX
#COLIBRI_WEBSOCKET_JVB_LOOKUP_NAME=jvb



# # # # # # # # # # # # # # # # # # # # # # # # #
#  JITSI MEET COMPONENTS CONFIGURATION SECTION  #
# # # # # # # # # # # # # # # # # # # # # # # # #


# # # # # # # # # # # # # # # # # # # # # # # # #
# Docker Compose options
#

# Container restart policy
RESTART_POLICY=always

# Jitsi image version (useful for local development)
JITSI_IMAGE_VERSION=stable-9955


# # # # # # # # # # # # # # # # # # # # # # # # #
# Let's Encrypt configuration
#

# Enable Let's Encrypt certificate generation
#ENABLE_LETSENCRYPT=0

# Domain for which to generate the certificate
#LETSENCRYPT_DOMAIN=meet.example.com

# E-Mail for receiving important account notifications (mandatory)
#LETSENCRYPT_EMAIL=alice@atlanta.net

# Use the staging server (for avoiding rate limits while testing)
#LETSENCRYPT_USE_STAGING=1


# # # # # # # # # # # # # # # # # # # # # # # # #
# Basic Jigasi SIP configuration options (needed for SIP gateway support)
#

# SIP URI for incoming / outgoing calls
#JIGASI_SIP_URI=test@sip2sip.info

# Password for the specified SIP account as a clear text
#JIGASI_SIP_PASSWORD=passw0rd

# SIP server (use the SIP account domain if in doubt)
#JIGASI_SIP_SERVER=sip2sip.info

# SIP server port
#JIGASI_SIP_PORT=5060

# SIP server transport
#JIGASI_SIP_TRANSPORT=UDP


# # # # # # # # # # # # # # # # # # # # # # # # #
# Recording / live-streaming configuration with Jibri
#

# Enable recording / live-streaming
ENABLE_RECORDING=1

# Directory for recordings inside Jibri container
JIBRI_RECORDING_DIR=/config/recordings

# The finalizing script. Will run after recording is complete
JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize-script.sh

# Prefix domain for strip inside Jibri (please see env.example for details)
JIBRI_STRIP_DOMAIN_JID=muc

# MUC name for the Jibri pool
JIBRI_BREWERY_MUC=jibribrewery

# MUC connection timeout
JIBRI_PENDING_TIMEOUT=180


# # # # # # # # # # # # # # # # # # # # # # # # #
# Whiteboard integration
#

# Set the excalidraw-backend URL in the docker local network (uncomment to enable)
#WHITEBOARD_COLLAB_SERVER_URL_BASE=http://whiteboard.meet.jitsi

# Set the excalidraw-backend public URL (uncomment to enable)
WHITEBOARD_COLLAB_SERVER_PUBLIC_URL=https://whiteboard.my.domain


# # # # # # # # # # # # # # # # # # # # # # # # #
# Etherpad integration (for document sharing)
#

# Set etherpad-lite URL in docker local network (uncomment to enable)
#ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001

# Set etherpad-lite public URL, including /p/ pad path fragment (uncomment to enable)
#ETHERPAD_PUBLIC_URL=https://etherpad.my.domain/p/

# Name your etherpad instance!
ETHERPAD_TITLE="Avroid Video Chat"

# The default text of a pad
ETHERPAD_DEFAULT_PAD_TEXT="Welcome to Avroid Web Chat!\n\n"

# Name of the skin for etherpad
ETHERPAD_SKIN_NAME=colibris

# Skin variants for etherpad
ETHERPAD_SKIN_VARIANTS="super-light-toolbar super-light-editor light-background full-width-editor"


# # # # # # # # # # # # # # # # # # # # # # # # #
# Basic Jigasi configuration options (needed for SIP gateway support)
#

# SIP URI for incoming / outgoing calls
#JIGASI_SIP_URI=test@sip2sip.info

# Password for the specified SIP account as a clear text
#JIGASI_SIP_PASSWORD=passw0rd

# SIP server (use the SIP account domain if in doubt)
#JIGASI_SIP_SERVER=sip2sip.info

# SIP server port
#JIGASI_SIP_PORT=5060

# SIP server transport
#JIGASI_SIP_TRANSPORT=UDP


# # # # # # # # # # # # # # # # # # # # # # # # #
# JaaS Components (beta)
# https://jaas.8x8.vc
#

# Enable JaaS Components (hosted Jigasi)
# NOTE: if Let's Encrypt is enabled a JaaS account will be automatically created, using the provided email in LETSENCRYPT_EMAIL
#ENABLE_JAAS_COMPONENTS=0
```
