### ISSUE TITLE
Jibri Docker Setup: "Stop Recording" UI State Not Updating in Jitsi Meet

### ISSUE THREAD

**Issue by anoop-singh-dev** [jitsi/jibri#575]
### What happened?

Description:
I'm using a Docker-based Jibri setup and encountering an issue where the Jitsi Meet UI does not update properly when stopping a recording.

Environment:

- Jitsi Meet: Installed on a separate server (non-Docker)

- Jibri: Running in Docker on a different server

- Storage: Recordings are uploaded to DigitalOcean Spaces via finalize_recording.sh

Issue:
When I start a recording:

- The recording starts successfully

- The file is saved and uploaded to DigitalOcean Spaces as expected

- However, when I click "Stop Recording" in the Jitsi Meet front end:

- The backend finishes the recording correctly and uploads the file

- But the recording indicator remains visible, and

- The "Stop Recording" button does not revert back to "Start Recording"

Important Notes:
- This issue only occurs with the Docker-based Jibri setup

- When I run Jibri without Docker on a standalone server, the stop functionality and UI update work as expected

Additional Info:
- Docker setup uses standard Jibri image with some modifications to support DigitalOcean Spaces in finalize_recording.sh

- No errors are seen in the browser console or Jibri logs when stopping the recording

Expected Behavior:
The Jitsi Meet front end should remove the recording indicator and switch the "Stop Recording" button back to "Start Recording" after a successful stop

Used yml file for container setup:

```
version: '3'
services:
  jibri-1:
    image: jitsi/jibri:stable-10008
    container_name: jibri-1
    restart: unless-stopped
    network_mode: "host"
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
      - NET_BIND_SERVICE
    devices:
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri  # Add GPU access
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - ./recordings:/config/recordings
      - ./finalize_recording.sh:/config/finalize_recording.sh
      - ./logs:/config/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Add X11 socket
    environment:
      - XMPP_AUTH_DOMAIN=auth.domain_name.com
      - XMPP_INTERNAL_MUC_DOMAIN=internal.auth.domain_name.com
      - XMPP_RECORDER_DOMAIN=recorder.domain_name.com
      - XMPP_SERVER=domain_name.com
      - XMPP_DOMAIN=domain_name.com
      - JIBRI_XMPP_USER=jibri1
      - JIBRI_XMPP_PASSWORD=jibri1pass
      - JIBRI_BREWERY_MUC=jibriBrewery
      - JIBRI_RECORDER_USER=recorder1
      - JIBRI_RECORDER_PASSWORD=recorder1pass
      - DISPLAY=:0
      - JIBRI_STRIP_DOMAIN_JID=true
      - JIBRI_LOGS_DIR=/config/logs
      - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize_recording.sh
      - JIBRI_USAGE_TIMEOUT=0
      - JIBRI_PENDING_TIMEOUT=90
      - JIBRI_XMPP_PORT=5222
      - JIBRI_HTTP_API_EXTERNAL_PORT=2222
      - JIBRI_HTTP_API_INTERNAL_PORT=3333
      - ENABLE_STATS_D=false
      - TZ=Asia/Kolkata
      # Add Chrome/browser specific settings
      - CHROME_DISABLE_GPU_SANDBOX=true
      - JIBRI_CHROME_FLAGS=--use-fake-ui-for-media-stream,--start-maximized,--kiosk,--enabled,--disable-infobars,--autoplay-policy=no-user-gesture-required,--ignore-certificate-errors,--disable-dev-shm-usage

  jibri-2:
    image: jitsi/jibri:stable-10008
    container_name: jibri-2
    restart: unless-stopped
    network_mode: "host"
    shm_size: 2gb
    cap_add:
      - SYS_ADMIN
      - NET_BIND_SERVICE
    devices:
      - /dev/snd:/dev/snd
      - /dev/dri:/dev/dri  # Add GPU access
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime:ro
      - ./recordings:/config/recordings
      - ./finalize_recording.sh:/config/finalize_recording.sh
      - ./logs:/config/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Add X11 socket
    environment:
      - XMPP_AUTH_DOMAIN=auth.meet.thelattice.org
      - XMPP_INTERNAL_MUC_DOMAIN=internal.auth.domain_name.com
      - XMPP_RECORDER_DOMAIN=recorder.domain_name.com
      - XMPP_SERVER=domain_name.com
      - XMPP_DOMAIN=domain_name.com
      - JIBRI_XMPP_USER=jibri2
      - JIBRI_XMPP_PASSWORD=jibri2pass
      - JIBRI_BREWERY_MUC=jibriBrewery
      - JIBRI_RECORDER_USER=recorder2
      - JIBRI_RECORDER_PASSWORD=recorder2pass
      - DISPLAY=:0
      - JIBRI_STRIP_DOMAIN_JID=true
      - JIBRI_LOGS_DIR=/config/logs
      - JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize_recording.sh
      - JIBRI_USAGE_TIMEOUT=0
      - JIBRI_PENDING_TIMEOUT=90
      - JIBRI_XMPP_PORT=5222
      - JIBRI_HTTP_API_EXTERNAL_PORT=2223
      - JIBRI_HTTP_API_INTERNAL_PORT=3334
      - ENABLE_STATS_D=false
      - TZ=Asia/Kolkata
      # Add Chrome/browser specific settings
      - CHROME_DISABLE_GPU_SANDBOX=true
      - JIBRI_CHROME_FLAGS=--use-fake-ui-for-media-stream,--start-maximized,--kiosk,--enabled,--disable-infobars,--autoplay-policy=no-user-gesture-required,--ignore-certificate-errors,--disable-dev-shm-usage

### Platform

- [x] Chrome (or Chromium based)
- [ ] Firefox
- [ ] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Version 136.0.7103.114 (Official Build) (64-bit)

### Relevant log output

```shell

```

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si
